Updated install script and updated Nikola binomial pricer

diff --git a/scripts/install-hsenv b/scripts/install-hsenv
--- a/scripts/install-hsenv
+++ b/scripts/install-hsenv
@@ -12,7 +12,11 @@
 
 set +e
 
-ROOT=`pwd`
+PATH=~/.cabal/bin/:/usr/local/cuda-4.2/bin/:$PATH
+LD_LIBRARY_PATH=/usr/local/cuda-4.2/lib #:$LD_LIBRARY_PATH
+
+
+ROOT=~/
 cd $ROOT
 
 BASEPATH=$PATH
@@ -37,7 +41,7 @@ init_hsenv() {
   NAME=$1
   GHC_VERSION=$2
   GHC_DIR=$ROOT/ghc/ghc-$GHC_VERSION
-  INSTALL_DIR=$ROOT/$NAME-GHC$GHC_VERSION/
+  INSTALL_DIR=$ROOT/hsenvs/$NAME-GHC$GHC_VERSION/
 
   if [ -d $INSTALL_DIR ]; then
     echo "$INSTALL_DIR already exists, using old installation"
@@ -55,13 +59,11 @@ init_hsenv() {
 
 installCUDAFromHackage (){
   # Fix and install cuda bindings
-  PATH=~/.cabal/bin/:/usr/local/cuda-4.2/bin/:$PATH
-  LD_LIBRARY_PATH=/usr/local/cuda-4.2/lib:$LD_LIBRARY_PATH
   cabal unpack cuda
   cd cuda-*
   sed -i -e "s/import Foreign.CUDA.Driver.Exec$/import Foreign.CUDA.Driver.Exec hiding \(Max\)/" Foreign/CUDA/Driver.hs 
   autoconf
-  cabal install --extra-include-dirs=/usr/local/cuda-4.2/include/
+  cabal install --extra-include-dirs=/usr/local/cuda-4.2/include/ --extra-lib-dirs=/usr/local/cuda-4.2/lib64/
   cd ..
 }
 
@@ -112,6 +114,7 @@ installNikola() {
   init_hsenv "nikola" "7.4.2"
 
     installCUDAFromHackage
+    cabal install repa-3.2.1.1
     cabal install test-framework-quickcheck2 test-framework-hunit
 
     git clone git://github.com/mainland/nikola.git
@@ -121,7 +124,7 @@ installNikola() {
         --disable-library-profiling \
         --enable-tests \
         --flags=examples \
-        --configure-option="--with-nvcc=/usr/local/cuda/bin/nvcc"
+        --configure-option="--with-nvcc=/usr/local/cuda-4.2/bin/nvcc"
 
     cabal build
     cabal install
@@ -150,8 +153,69 @@ installObsidian() {
   deactivate_hsenv
 }
 
-#installObsidian
-#installFeldspar
-#installAccelerateFromHackage
-installNikola
-#installAccelerateFromGithub
+installDPH() {
+  init_hsenv "dph" "7.4.2"
+  cabal install dph-examples
+  deactivate_hsenv
+}
+
+show_usage() {
+  echo "This command installs GHC environments for different Haskell vector languages"
+  echo ""
+  echo "Invoke with one or more of the following flags:"
+  echo "  --nikola"
+  echo "  --obsidian"
+  echo "  --feldspar"
+  echo "  --dph"
+  echo "  --accelereate-github"
+  echo "  --accelereate-hackage"
+}
+
+
+if [ $# -lt 1 ]; then
+    echo "No arguments given. Aborting."
+    echo ""
+    show_usage
+    exit 1
+fi
+
+while [ $# -gt 0 ]; do
+  case $1 in
+  --nikola)
+    installNikola
+    shift
+    continue
+    ;;
+  --feldspar)
+    installFeldspar
+    shift
+    continue
+    ;;
+  --accelerate-github)
+    installAccelerateFromGithub
+    shift
+    continue
+    ;;
+  --accelerate-hackage)
+    installAccelerateFromHackage
+    shift
+    continue
+    ;;
+  --obsidian)
+    installObsidian
+    shift
+    continue
+    ;;
+  --dph)
+    installDPH
+    shift
+    continue
+    ;;
+  *)
+    echo "Unknown parameter $1"
+    shift
+    continue
+    ;;
+  esac
+break
+done
